print("Program starting.")
Brand = input("Insert car brand: ")
Model = input("Insert car model: ")
print(f"Car brand is \"{Brand}\" ", end="")
print(f"and the model is \'{Model}\'.")
print("Program ending.")