print("Program starting.")
first_word = input("Insert first word: ")
second_word = input("Insert second word: ")
print(f"1st word is {len(first_word)} characters long.")
print(f"2nd word is {second_word} characters long.")
print(f"Words together make one closed compound '{first_word}{second_word}'.")
print("Program ending.")